language: node_js
node_js:
  - "node"

before_install:
  - npm install -g npm@latest

install:
  - npm install

before_script:
  - npm install gulp gulp-uglify 
  - npm install gulp-rename gulp-babel babel-preset-env --save-dev
  - npm install --save-dev eslint

script:
  - npm run test

notifications:
  email: false